import Head from "next/head";
import { Navigation } from "@/components/navigation";
import { Bubbles } from "@/components/bubbles";
import { Footer } from "@/components/footer";
import { Label } from "@/components/label";
import client from "@/apollo-client";
import { gql } from "@apollo/client";
import limit from "@/lib/limit";
import { useState } from "react";
import { formatDateDutch } from "@/lib/formatDateDutch";
import { sortEventsByDate } from "@/lib/sortEventsByDate";
import { getEventsFromHipsy } from "@/lib/getEventsFromHipsy";
import { formatHipsyAddress } from "@/lib/formatHipsyAddress";
import { EventItem } from "@/components/eventItem";
import { getEventsFromFacebook } from "@/lib/getEventsFromFacebook";
import { uniqueEvents } from "@/lib/uniqueEvents";
